Repository INOI-SWM/RidingMate_Flutter, pull requests merged in 2025-06, with the labels that each got.

#6 [Chore]: 컬러시스템 구성
  lib/core/theme/app_theme.dart
  lib/core/theme/extensions.dart
  lib/core/theme/semantic_colors.dart
  lib/design_system/atomic/atomic_colors.dart
Labels: 🧹 chore

#10 [Feat] create button text
  lib/design_system/button/button_text.dart
Labels: ✨ feat

#14 feat: 썸네일 위젯 구현
  lib/design_system/thumbnail/thumbnail.dart
Labels: ✨ feat

#13 [Feat] create chip action
  .lefthook/validate-commit-msg.sh
  lefthook.yml
  lib/design_system/chip/chip_action.dart
Labels: ✨ feat

#19 [Feat]poi setting grid 생성
  lib/ui/settings/poi_settings_grid.dart
Labels: ✨ feat

#20 [Fix] fix lefthook error
  .lefthook/flutter-analyze.sh
  lefthook.yml
Labels: 🐛 fix, 🧹 chore

#23 [Feat] 주행하기 버튼 추가
  assets/icons/svg/play.svg
  lib/design_system/ride_button/ride_button.dart
Labels: ✨ feat

#21 [Feat] search field 위젯 구현
  assets/icons/svg/circle_close_fill.svg
  lib/design_system/input/search_field.dart
Labels: ✨ feat

#24 [Feat] top navigation 위젯 구현
  .lefthook/flutter-analyze.sh
  lib/design_system/navigation/top_navigation_bar.dart
Labels: ✨ feat

#28 [Feat] CardNormal, 즐겨찾기 토글 구현
  .gitignore
  assets/images/png/thumbnail_r21_9.png
  assets/images/png/thumbnail_r3_2.png
  lib/design_system/button/favorite_toggle.dart
  lib/design_system/card/card_list.dart
  lib/design_system/card/card_normal.dart
  pubspec.yaml
Labels: ✨ feat

#31 [Design]card list 불필요한 padding제거
  lib/design_system/card/card_list.dart
  lib/design_system/card/card_normal.dart
Labels: ✨ feat

#30 [Feat] search bar 구현 및 scaffold변경
  lib/design_system/input/base_search_field.dart
  lib/design_system/input/search_field.dart
  lib/design_system/input/search_field_preview.dart
  lib/design_system/input/search_field_size.dart
  lib/design_system/navigation/floating_search_navigation_bar.dart
  lib/design_system/navigation/search_navigation_bar.dart
  lib/design_system/navigation/top_navigation_bar.dart
  lib/ui/navigation/navigation_scaffold.dart
  lib/ui/screens/page_with_app_bar.dart
Labels: ✨ feat

#34 [Feat] 현재위치로 이동 버튼 생성
  lib/ui/screens/riding_screen.dart
Labels: ✨ feat

#35 [Feat]map에 pin찍기 구현
  lib/ui/screens/riding_screen.dart
Labels: ✨ feat

#36 [Feat] 핀 찍기 되돌리기 추가
  lib/design_system/button/icon_button_solid.dart
  lib/ui/screens/riding_screen.dart
Labels: ✨ feat

#37 [Feat] gpx 파일 외부로 공유
  android/app/build.gradle.kts
  lib/features/share_route/share_gpx_file.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#38 [Feat] 경로생성 및 폴리라인 그리기
  ios/Podfile.lock
  lib/design_system/map/route_pin_marker.dart
  lib/models/route_result.dart
  lib/services/location_service.dart
  lib/services/route_service.dart
  lib/ui/screens/riding_screen.dart
  lib/ui/widgets/poi_settings_grid.dart
  lib/ui/widgets/route_creation_actions.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#39 [Feat] 경로생성 시 경로에 대한 정보 보여주기
  lib/design_system/info/info_item.dart
  lib/design_system/navigation/top_navigation_bar.dart
  lib/models/route_api_response.dart
  lib/models/route_data.dart
  lib/models/route_result.dart
  lib/services/elevation_calculator.dart
  lib/services/route_api_client.dart
  lib/services/route_service.dart
  lib/ui/screens/riding_screen.dart
  lib/ui/widgets/route_creation_actions.dart
  lib/ui/widgets/route_info_bar.dart
Labels: ✨ feat, 🔨 refactor

#41 [refactor] 아이콘만있는 버튼의 크기 고정을 위해 사용하였던 sizedbox를 gesture detactor로 변경
  ios/Podfile.lock
  lib/design_system/modal/modal_popup.dart
  lib/design_system/navigation/floating_search_navigation_bar.dart
  lib/design_system/navigation/search_navigation_bar.dart
Labels: 🔨 refactor

#43 [Feat] 경로 데이터 인코더&디코더 구현, 저장 완료버튼 비활성화 로직 추가, 텍스트필드 오토포커싱
  lib/services/elevation_calculator.dart
  lib/services/route_service.dart
  lib/ui/screens/riding_screen.dart
  lib/ui/widgets/route_create_bottom_panel.dart
  lib/utils/polyline_utils.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#45 [Feat] 경로 to gpx 변환
  lib/utils/gpx_generator.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#47 [Feat] 경로 목록 화면 구현
  lib/features/route_list/application/services/route_list_service.dart
  lib/features/route_list/presentation/route_list_screen.dart
Labels: ✨ feat

#48 [Refactor]route_planning 폴더 clean architecture 적용
  analysis_options.yaml
  lib/features/route_planning/application/services/gpx_generator.dart
  lib/features/route_planning/application/services/route_api_client.dart
  lib/features/route_planning/application/services/route_service.dart
  lib/features/route_planning/application/use_cases/create_route_use_case.dart
  lib/features/route_planning/application/use_cases/get_current_location_use_case.dart
  lib/features/route_planning/application/use_cases/manage_route_pins_use_case.dart
  lib/features/route_planning/application/use_cases/route_planning_facade.dart
  lib/features/route_planning/application/use_cases/route_stats_use_case.dart
  lib/features/route_planning/application/use_cases/save_route_use_case.dart
  lib/features/route_planning/data/datasources/route_remote_datasource.dart
  lib/features/route_planning/data/exceptions/route_exceptions.dart
  lib/features/route_planning/data/mappers/route_mapper.dart
  lib/features/route_planning/data/models/route_api_response.dart
  lib/features/route_planning/data/models/route_api_response_model.dart
  lib/features/route_planning/data/repositories/route_repository_impl.dart
  lib/features/route_planning/domain/entities/route_data.dart
  lib/features/route_planning/domain/repositories/route_repository.dart
  lib/features/route_planning/domain/services/elevation_calculate_service.dart
  lib/features/route_planning/domain/services/polyline_convert_service.dart
  lib/features/route_planning/presentation/screens/route_planning_screen.dart
Labels: 🔨 refactor

#49 [Feat]google oauth연동 구현
  android/app/src/main/AndroidManifest.xml
  assets/icons/svg/apple_logo.svg
  assets/icons/svg/google_logo.svg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/features/login/application/di/login_di.dart
  lib/features/login/application/use_cases/sign_in_with_google_use_case.dart
  lib/features/login/data/datasources/google_auth_datasource.dart
  lib/features/login/data/repositories/auth_repository_impl.dart
  lib/features/login/domain/entities/user.dart
  lib/features/login/domain/repositories/auth_repository.dart
  lib/features/login/presentation/screens/login_screen.dart
  lib/features/login/presentation/widgets/login_button.dart
  lib/features/profile/presentation/screens/my_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#50 [Feat] riverpod 도입.
  lib/features/login/application/di/login_di.dart
  lib/features/login/di/auth_providers.dart
  lib/features/login/presentation/screens/login_screen.dart
  lib/features/route_planning/application/use_cases/manage_route_pins_use_case.dart
  lib/features/route_planning/di/route_providers.dart
  lib/features/route_planning/presentation/screens/route_planning_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat, 🔨 refactor

#51 [Feat] apple oauth 도입
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  ios/Runner/RunnerDebug.entitlements
  ios/build/ios/XCBuildData/PIFCache/project/PROJECT@v11_mod=bfff6c727fb4fa5c34fc69bf5577b48b_hash=bfdfe7dc352907fc980b868725387e98plugins=1OJSG6M1FOV3XYQCBH7Z29RZ0FPR9XDE1-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=020fcd998c89fc53905774187602f3a3-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=06a10f07c2229a1f5d34a7e8e57f8583-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=088fd88208f5eebeb5c26d02a29d3346-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=127e12f8fe0579a33c9f5af86525fae4-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=1a636b1ac11d3b6691b895638218c2de-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=20590f27b0f5c10e40df0e351d1c486b-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=2dc4e2939b2de4323336c531a50ff2e1-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=30d17d48664ab9476a7fc5707f4cd96b-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=584b9b3d941080cbf245794d3d30ffeb-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=66affdeb078fa598f418b7b2ca07ba11-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=6e07d36b4b81dc2b2d4eebf464e34cdd-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=801f100c6541dd6fec54397a7feeb08a-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=8077d293020b5060479a7726960871bf-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=8b31d942cc7528022c622c5ec4a38913-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=8f1cf3a1d8094e5f90f26e7147069abc-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=95c208c2682bc076e6719c2eb100f691-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=9f069d32a020954ac38517eb64e5c8a7-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=ae631def161d8a74769d468eb9de248e-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=b40713b21a87c9c850ba83ab3eb223c6-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=bfdd58e376ff277ac872b322b69c3de1-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=d4cedf5deabba8269e44f12bada802d8-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=df1b8ce29a6fef5e11a9c320e454d707-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=e4b14a24c60a96666ba3b3bf97e7cd7b-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=eb346893240fa6e40be1e1234a177a53-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=ed54833dc43be3db5cfc7b1f8198cb84-json
  ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=fc90020fc027ea7dcc2e5841504c25da-json
  ios/build/ios/XCBuildData/PIFCache/workspace/WORKSPACE@v11_hash=(null)_subobjects=0207e0b2ef8083031f3e130eb721817a-json
  lib/features/login/application/use_cases/sign_in_with_apple_use_case.dart
  lib/features/login/application/use_cases/sign_in_with_google_use_case.dart
  lib/features/login/data/datasources/apple_auth_datasource.dart
  lib/features/login/data/repositories/apple_auth_repository_impl.dart
  lib/features/login/data/repositories/google_auth_repository_impl.dart
  lib/features/login/di/auth_providers.dart
  lib/features/login/domain/repositories/apple_auth_repository.dart
  lib/features/login/domain/repositories/google_auth_repository.dart
  lib/features/login/presentation/screens/login_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#52 [Feat] kakao oauth 도입, android 패키지명 변경
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/ridingmate/MainActivity.kt
  android/app/src/main/kotlin/com/inoi/ridingmate/dev/MainActivity.kt
  assets/icons/svg/kakao_logo.svg
  devtools_options.yaml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/features/login/application/use_cases/sign_in_with_kakao_use_case.dart
  lib/features/login/data/datasources/kakao_auth_datasource.dart
  lib/features/login/data/repositories/kakao_auth_repository_impl.dart
  lib/features/login/di/auth_providers.dart
  lib/features/login/domain/repositories/kakao_auth_repository.dart
  lib/features/login/presentation/screens/login_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat, 🏗️ build

#53 [Feat] 경로 저장 단계에서 경로를 한눈에 보게 화면이동
  lib/features/route_planning/application/use_cases/save_route_use_case.dart
  lib/features/route_planning/data/mappers/route_mapper.dart
  lib/features/route_planning/data/models/route_api_response_model.dart
  lib/features/route_planning/domain/entities/route_data.dart
  lib/features/route_planning/domain/services/bbox_service.dart
  lib/features/route_planning/presentation/screens/route_planning_screen.dart
Labels: ✨ feat

#54 [feat] map tile server 변경
  lib/features/route_planning/presentation/screens/route_planning_screen.dart
Labels: ✨ feat

#57 [Feat] 로그인 후 각종 로직을 위한 유저 객체 provider로 관리
  lib/features/auth/application/providers/user_session_notifier.dart
  lib/features/login/data/repositories/apple_auth_repository_impl.dart
  lib/features/login/data/repositories/google_auth_repository_impl.dart
  lib/features/login/data/repositories/kakao_auth_repository_impl.dart
  lib/features/login/domain/entities/user.dart
  lib/features/login/presentation/screens/login_screen.dart
  lib/features/profile/presentation/pages/profile_page.dart
  lib/features/profile/presentation/screens/login_required_screen.dart
  lib/features/profile/presentation/screens/my_screen.dart
  lib/features/profile/presentation/screens/profile_screen.dart
  lib/main.dart
  lib/navigation/navigation_scaffold.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feat

#58 [Feat] google logout 도입
  lib/features/auth/application/providers/user_session_notifier.dart
  lib/features/auth/application/use_cases/auth_sign_in_facade.dart
  lib/features/auth/application/use_cases/auth_sign_out_facade.dart
  lib/features/auth/application/use_cases/sign_in_with_apple_use_case.dart
  lib/features/auth/application/use_cases/sign_in_with_google_use_case.dart
  lib/features/auth/application/use_cases/sign_in_with_kakao_use_case.dart
  lib/features/auth/application/use_cases/sign_out_with_apple_use_case.dart
  lib/features/auth/application/use_cases/sign_out_with_google_use_case.dart
  lib/features/auth/application/use_cases/sign_out_with_kakao_use_case.dart
  lib/features/auth/data/datasources/apple_auth_datasource.dart
  lib/features/auth/data/datasources/google_auth_datasource.dart
  lib/features/auth/data/datasources/kakao_auth_datasource.dart
  lib/features/auth/data/repositories/apple_auth_repository_impl.dart
  lib/features/auth/data/repositories/google_auth_repository_impl.dart
  lib/features/auth/data/repositories/kakao_auth_repository_impl.dart
  lib/features/auth/data/repositories/user_session_repository_impl.dart
  lib/features/auth/di/auth_providers.dart
  lib/features/auth/domain/entities/user.dart
  lib/features/auth/domain/enums/login_provider.dart
  lib/features/auth/domain/repositories/apple_auth_repository.dart
  lib/features/auth/domain/repositories/google_auth_repository.dart
  lib/features/auth/domain/repositories/kakao_auth_repository.dart
  lib/features/auth/domain/repositories/user_session_repository.dart
  lib/features/auth/presentation/screens/login_screen.dart
  lib/features/auth/presentation/widgets/login_button.dart
  lib/features/login/di/auth_providers.dart
  lib/features/profile/presentation/pages/profile_page.dart
  lib/features/profile/presentation/screens/login_required_screen.dart
  lib/features/profile/presentation/screens/profile_screen.dart
Labels: ✨ feat, 🔨 refactor
